# Makefile with dependencies management (Q4)

CXX        = g++
CXXFLAGS   = -Wall -std=c++11
DEPFLAGS   = -MMD
LDFLAGS    =
SRCS       = chambre_test.cpp chambre.cpp
OBJS       = $(SRCS:.cpp=.o)
TARGET     = chambre_test
DEPS	   = $(OBJS:.o=.d)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $(TARGET) $(OBJS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(DEPFLAGS) -c  $<

clean:
	rm -f *.o *.d

mrproper: clean
	rm -f $(TARGET)

exe: $(TARGET)
	./$(TARGET)

-include $(DEPS)
